enzymes:
  coordinator:
    dataset: enzymes
    params_edit_cost: !!python/tuple [1.0, 1.0, 1.0, 1.0, euclidean]
    folder_dataset: ./data_gnn/reduced_graphs_ENZYMES_full_1932/data/
  folder_results: ./results_gnn/knn/enzymes_full_1932
general:
  optimize: True
  tuning:
    alpha: [10, 20, 0.05]
    ks: [1] #, 3, 5]
  num_cores: 12
  parallel: True
  save_predictions: True
  save_dist_matrix: False
