cdef:
    str EXTENSION_GRAPHS
    str EXTENSION_GRAPHML
    str EXTENSION_SPLITS

    dict DEFAULT_FOLDERS
    dict DEFAULT_FOLDERS_GNN_EMBEDDING
    dict DEFAULT_FOLDERS_LABELS
    dict DEFAULT_FOLDERS_GNN_EMBEDDING_LABELS

    dict LETTER_LBL_TO_CODE
    dict AIDS_LBL_TO_CODE
    dict MUTAGENICITY_LBL_TO_CODE
    dict NCI1_LBL_TO_CODE
    dict PROTEINS_TU_LBL_TO_CODE
    dict ENZYMES_TO_CODE
    dict COLLAB_TO_CODE
    dict REDDIT_BINARY_TO_CODE
    dict IMDB_BINARY_TO_CODE
    dict DEFAULT_LABELS_TO_CODE

    list PERCENT_HIERARCHY
