letter:
  coordinator:
    dataset: letter
    params_edit_cost: !!python/tuple [1.0, 1.0, 1.0, 1.0, euclidean]
    folder_dataset: ./data/Letter/Letter/HIGH/
  k: 5
  best_alpha: 0.55

  # score
  linear_combination: [0.9, 0.7, 0.4, 0.2, 0.4]
  folder_results: ./results/knn_linear_combination_v2/letter
AIDS:
  coordinator:
    dataset: AIDS
    params_edit_cost: !!python/tuple [1.0, 1.0, 1.0, 1.0, dirac]
    folder_dataset: ./data/AIDS/data/
  k: 1
  best_alpha: 0.7
  knn_lc_params:
    # dist
    # grid search
    # omegas: [0.1, 0.1, 0.1, 0.1, 0.2]
    # genetic
    # omegas: [0.595, 0.53,  0.419, 0.335, 0.623]

    # score
    # grid search
    # omegas: [0.1, 0.1, 0.2, 0.3, 0.3]
    # genetic
    omegas: [0.1, 0.1, 0.1, 0.1, 0.3]

  folder_results: ./results/knn_linear_combination_v2/AIDS
mutagenicity:
  coordinator:
    dataset: mutagenicity
    params_edit_cost: !!python/tuple [1.0, 1.0, 1.0, 1.0, dirac]
    folder_dataset: ./data/Mutagenicity/data/
    folder_labels: ./data/Mutagenicity/data/
  k: 5
  best_alpha: 0.60
  # dist
  knn_lc_params:
    # dist
    # grid search
     omegas: [0.2, 0.3, 0.4, 0.1, 0.9]
    # genetic
    # omegas: [0.39721598, 0.10639951, 0.01008498, 0.26027967, 0.64930217]

    # score
    # grid search
    # omegas: [0.1, 0.5, 0.1, 0.4, 0.1]
    # genetic
    # omegas: [0.0, 0.575, 0.287, 0.0, 0.487]
  folder_results: ./results/knn_linear_combination_v2/mutagenicity
NCI1:
  coordinator:
    dataset: NCI1
    params_edit_cost: !!python/tuple [1.0, 1.0, 1.0, 1.0,  dirac]
    folder_dataset: ./data/NCI1/data/
    folder_labels: ./data/NCI1/data/
  k: 5
  best_alpha: 0.7
  # dist
  knn_lc_params:
    # dist
    # grid search
    # omegas: [0.8, 0.3, 0.7, 0.3, 0.2]
    # genetic
    omegas: [0.787, 0.186, 0.445, 0.489, 0.059]

    # score
    # grid search
    # omegas: [0.1, 0.0, 0.0, 0.0, 0.0]
    # genetic
    # omegas: [0.8392, 0.0758, 0.3402, 0.3316, 0.0644]
  folder_results: ./results/knn_linear_combination_v2/NCI1
proteins_tu:
  coordinator:
    dataset: proteins_tu
    params_edit_cost: !!python/tuple [1.0, 1.0, 1.0, 1.0, dirac]
    folder_dataset: ./data/PROTEINS/data/
  k: 3
  best_alpha: 0.9
  #dist
  knn_lc_params:

    # dist
    # grid search
    # omegas: [0.3, 0.1, 0.1, 0.0, 0.0]
    # genetic
    omegas: [0.67644065, 0.05247464, 0.0500646, 0.0041038, 0.06416552]

    # score
    # grid search
    # omegas: [1.0, 1.0, 1.0, 1.0, 1.0]
    # genetic
    # omegas: [0.765, 0.284, 0.19,  0.471, 0.335]

  folder_results: ./results/knn_linear_combination_v2/proteins_tu
enzymes:
  coordinator:
    dataset: enzymes
    params_edit_cost: !!python/tuple [1.0, 1.0, 1.0, 1.0, dirac]
    folder_dataset: ./data/ENZYMES/data/
  k: 1
  best_alpha: 0.9
  #dist
  knn_lc_params:
    # dist
    # grid search
    # omegas: [0.8, 0.6, 0.4, 0.1, 0.2]
    # genetic
    # omegas: [0.82462416, 0.20272117, 0.13497033, 0.08721029, 0.49654426]

    # score
    # grid search
    # omegas: [0.9, 0.5, 0.1, 0.1, 0.2]
    # genetic
     omegas: [0.828, 0.276, 0.126, 0.563, 0.267]

  folder_results: ./results/knn_linear_combination_v2/enzymes
IMDB_binary:
  coordinator:
    dataset: IMDB_binary
    params_edit_cost: !!python/tuple [1.0, 1.0, 1.0, 1.0, dirac]
    folder_dataset: ./data/IMDB-BINARY/data/
  k: 5
  best_alpha: 0.95

  knn_lc_params:
    # dist
    # grid search
    # omegas: [0.7, 0.8, 0.3, 0.9, 0.6]
    # genetic
    # omegas: [0.72539422, 0.65570383, 0.24220956, 0.49781663, 0.23224303]

    # score
    # grid search
    # omegas: [0.4, 0.0, 0.0, 0.1, 0.3]
    # genetic
    omegas: [0.7824, 0.0758, 0.2796, 0.1994, 0.0644]
  folder_results: ./results/knn_linear_combination_v2/IMDB_binary
general:
  hierarchy_params:
#    percentages: [1.0, 0.9, 0.8, 0.7, 0.6, 0.5, 0.4, 0.3, 0.2] # , 0.1]
    percentages: [1.0, 0.8, 0.6, 0.4, 0.2]
    centrality_measures: [pagerank] # betweenness]
  centrality_measure: pagerank # betweenness
  augmented_random_graphs: False
  num_sub_bunch: 1
  parallel: True
  deletion_strategy: compute_once
  save_predictions: True
  optimization_strategy: genetic_algorithm #  grid_search
  num_cores: 12
  optimize: False
  cv: 5
  dist: False
  ga_params:
    num_generations: 200
    num_parents_mating: 4
    sol_per_pop: 20
    # single_point, uniform, scattered
    crossover_type: uniform
    # random, swap, inversion, scramble, adaptive
    mutation_type: adaptive
    # sss, rws, sus, rank, tournament
    parent_selection_type: tournament
    mutation_probability: [0.25, 0.1]
#    mutation_probability: 0.4
    gene_space:
      low: 0.0
      high: 1.0