letter:
  coordinator:
    dataset: letter
    params_edit_cost: !!python/tuple [0.9, 0.9, 2.3, 2.3, euclidean]
    folder_dataset: ./data/Letter/Letter/HIGH/
  folder_results: ./results/hierarchical/letter
AIDS:
  coordinator:
    dataset: AIDS
    params_edit_cost: !!python/tuple [1.1, 1.1, 0.1, 0.1, dirac]
    folder_dataset: ./data/AIDS/data/
  folder_results: ./results/hierarchical/AIDS
mutagenicity:
  coordinator:
    dataset: mutagenicity
    params_edit_cost: !!python/tuple [11.0, 11.0, 1.1, 1.1, dirac]
    folder_dataset: ./data/Mutagenicity/data/
  folder_results: ./results/hierarchical/mutagenicity
NCI1:
  coordinator:
    dataset: NCI1
    params_edit_cost: !!python/tuple [11.0, 11.0, 1.1, 1.1, dirac]
    folder_dataset: ./data/NCI1/data/
  folder_results: ./results/hierarchical/NCI1
proteins_tu:
  coordinator:
    dataset: proteins_tu
    params_edit_cost: !!python/tuple [11.0, 11.0, 1.1, 1.1, dirac]
    folder_dataset: ./data/PROTEINS/data/
  folder_results: ./results/hierarchical/proteins_tu
enzymes:
  coordinator:
    dataset: enzymes
    params_edit_cost: !!python/tuple [11.0, 11.0, 1.1, 1.1, dirac]
    folder_dataset: ./data/ENZYMES/data/
  folder_results: ./results/hierarchical/enzymes
general:
  num_graphs: 100
  random_graph: True
  percentage: 1.0
  centrality_measure: pagerank
  save_to_html: True

