letter:
  coordinator:
    dataset: letter
    params_edit_cost: !!python/tuple [1.0, 1.0, 1.0, 1.0, euclidean]
    folder_dataset: ./data/Letter/Letter/HIGH/
  k: 5
  best_alpha: 0.55
  folder_results: ./results/h_knn/letter
AIDS:
  coordinator:
    dataset: AIDS
    params_edit_cost: !!python/tuple [1.0, 1.0, 1.0, 1.0, dirac]
    folder_dataset: ./data/AIDS/data/
  k: 1
  best_alpha: 0.7
  folder_results: ./results/h_knn/AIDS
mutagenicity:
  coordinator:
    dataset: mutagenicity
    params_edit_cost: !!python/tuple [1.0, 1.0, 1.0, 1.0, dirac]
    folder_dataset: ./data/Mutagenicity/data/
    folder_labels: ./data/Mutagenicity/data/
  k: 3
  best_alpha: 0.60
  folder_results: ./results/h_knn/mutagenicity
NCI1:
  coordinator:
    dataset: NCI1
    params_edit_cost: !!python/tuple [1.0, 1.0, 1.0, 1.0,  dirac]
    folder_dataset: ./data/NCI1/data/
    folder_labels: ./data/NCI1/data/
  k: 5
  best_alpha: 0.7
  folder_results: ./results/h_knn/NCI1
general:
  finetune: False
  tuning:
    alpha: [1, 20, 0.05]
    ks: [1, 3, 5]
  hierarchy_params:
    percentages: [1.0, 0.8, 0.6, 0.4, 0.2]
    centrality_measures: [pagerank, betweenness]
  centrality_measure: pagerank
  parallel: True
  deletion_strategy: compute_once
  save_to_html: False
  save_predictions: True
