letter:
  coordinator:
    dataset: letter
    params_edit_cost: !!python/tuple [0.9, 0.9, 2.3, 2.3, euclidean, 0.75]
    folder_dataset: ./data/Letter/Letter/HIGH/
    folder_labels: ./data/Letter/Letter/HIGH/
  k: 5
AIDS:
  coordinator:
    dataset: AIDS
    params_edit_cost: !!python/tuple [1.1, 1.1, 0.1, 0.1, dirac, 0.25]
    folder_dataset: ./data/AIDS/data/
    folder_labels: ./data/AIDS/data/
  k: 1
mutagenicity:
  coordinator:
    dataset: mutagenicity
    params_edit_cost: !!python/tuple [11.0, 11.0, 1.1, 1.1, dirac, 0.75]
    folder_dataset: ./data/Mutagenicity/data/
    folder_labels: ./data/Mutagenicity/data/
  k: 5
NCI1:
  coordinator:
    dataset: NCI1
    params_edit_cost: !!python/tuple [11.0, 11.0, 1.1, 1.1, dirac, 0.75]
    folder_dataset: ./data/NCI1/data/
    folder_labels: ./data/NCI1/data/
  k: 5
proteins_tu:
  coordinator:
    dataset: proteins_tu
    params_edit_cost: !!python/tuple [1.0, 1.0, 1.0, 1.0, dirac, 0.75]
    folder_dataset: ./data/PROTEINS/data/
    folder_labels: ./data/PROTEINS/data/
  k: 5
enzymes:
  coordinator:
    dataset: enzymes
    params_edit_cost: !!python/tuple [1.0, 1.0, 1.0, 1.0, dirac, 0.75]
    folder_dataset: ./data/ENZYMES/data/
    folder_labels: ./data/ENZYMES/data/
  k: 5
collab:
  coordinator:
    dataset: collab
    params_edit_cost: !!python/tuple [1.0, 1.0, 1.0, 1.0, dirac, 0.75]
    folder_dataset: ./data/COLLAB/data/
    folder_labels: ./data/COLLAB/data/
  k: 5
general:
  parallel: True
