AIDS:
  coordinator:
    dataset: AIDS
    params_edit_cost: !!python/tuple [1.0, 1.0, 1.0, 1.0, dirac]
    folder_dataset: ./data/AIDS/data/
  k: 1
  best_alpha: 0.7
  folder_results: ./results/bagging_knn/AIDS
  bagging_params:
    n_estimators: 160
    percentage_train_data: 1.0
    random_k: True
    lambdas: [1.0, 0.8, 0.6, 0.4, 0.2]
mutagenicity:
  coordinator:
    dataset: mutagenicity
    params_edit_cost: !!python/tuple [1.0, 1.0, 1.0, 1.0, dirac]
    folder_dataset: ./data/Mutagenicity/data/
    folder_labels: ./data/Mutagenicity/data/
  k: 5
  best_alpha: 0.60
  folder_results: ./results/bagging_knn/mutagenicity
  bagging_params:
    n_estimators: 106
    percentage_train_data: 2.0
    random_k: True
    lambdas: [1.0, 0.8, 0.6, 0.4, 0.2]
NCI1:
  coordinator:
    dataset: NCI1
    params_edit_cost: !!python/tuple [1.0, 1.0, 1.0, 1.0,  dirac]
    folder_dataset: ./data/NCI1/data/
    folder_labels: ./data/NCI1/data/
  k: 5
  best_alpha: 0.7
  folder_results: ./results/bagging_knn/NCI1
  bagging_params:
    n_estimators: 134
    percentage_train_data: -1
    random_k: -1
    lambdas: -1
general:
  hierarchy_params:
    percentages: [1.0, 0.8, 0.6, 0.4, 0.2]
  centrality_measure: betweenness
  parallel: True
  deletion_strategy: compute_once
  num_cores: 12
  optimize: True
  use_reduced_graphs: True
  fine_tuning:
    # range of values for the number of estimators: [start, end, step]
    n_estimators: [60, 100, 20]
    lambdas: [[1.0, 0.8, 0.6, 0.4, 0.2]] # , [1.0, 0.8, 0.6, 0.4], [1.0, 0.8, 0.6], [1.0, 0.8]]
    percentage_data_train: [1.0, 1.5, 2.0] # [0.8, 1.0, 1.2, 1.4]
    random_k: [True] # [False, True]
