letter:
  coordinator:
    dataset: letter
    params_edit_cost: !!python/tuple [1.0, 1.0, 1.0, 1.0, euclidean]
    folder_dataset: ./data/Letter/Letter/HIGH/
  k: 5
  best_alpha: 0.55
  folder_results: ./results/coarse_to_fine/letter
AIDS:
  coordinator:
    dataset: AIDS
    params_edit_cost: !!python/tuple [1.0, 1.0, 1.0, 1.0, dirac]
    folder_dataset: ./data/AIDS/data/
  k: 5
  best_alpha: 0.7
  folder_results: ./results/coarse_to_fine/AIDS
mutagenicity:
  coordinator:
    dataset: mutagenicity
    params_edit_cost: !!python/tuple [1.0, 1.0, 1.0, 1.0, dirac]
    folder_dataset: ./data/Mutagenicity/data/
    folder_labels: ./data/Mutagenicity/data/
  k: 5
  best_alpha: 0.60
  folder_results: ./results/coarse_to_fine/mutagenicity
NCI1:
  coordinator:
    dataset: NCI1
    params_edit_cost: !!python/tuple [1.0, 1.0, 1.0, 1.0,  dirac]
    folder_dataset: ./data/NCI1/data/
    folder_labels: ./data/NCI1/data/
  k: 5
  best_alpha: 0.7
  folder_results: ./results/coarse_to_fine/NCI1
general:
  exp: pt4
  limit: 4
  percentage_remaining_graphs: 0.1
  hierarchy_params:
    percentages: [1.0, 0.2]
    centrality_measures: [pagerank] # , betweenness]
  current_centrality_measure: pagerank
  deletion_strategy: compute_once
  save_predictions: True
  num_cores: 24
  parallel: True
