AIDS:
  coordinator:
    dataset: AIDS
    params_edit_cost: !!python/tuple [1.0, 1.0, 1.0, 1.0, dirac]
    folder_dataset: ./data/AIDS/data/
  h_knn:
    current_percentage: 1.0
    1.0:
      k: 3
      alpha: 0.95
    # PageRank
    0.8:
      k: 1
      alpha: 0.95
    0.6:
      k: 7
      alpha: 0.95
    0.4:
      k: 1
      alpha: 0.65
    0.2:
      k: 3
      alpha: 0.95
  folder_results: ./results/h_knnV2/AIDS
mutagenicity:
  coordinator:
    dataset: mutagenicity
    params_edit_cost: !!python/tuple [1.0, 1.0, 1.0, 1.0, dirac]
    folder_dataset: ./data/Mutagenicity/data/
  h_knn:
    current_percentage: 1.0
    1.0:
      k: 5
      alpha: 0.75
    # PageRank
    0.8:
      k: 3
      alpha: 0.95
    0.6:
      k: 5
      alpha: 0.95
    0.4:
      k: 3
      alpha: 0.9
    0.2:
      k: 7
      alpha: 0.9
  folder_results: ./results/h_knnV2/mutagenicity
NCI1:
  coordinator:
    dataset: NCI1
    params_edit_cost: !!python/tuple [1.0, 1.0, 1.0, 1.0,  dirac]
    folder_dataset: ./data/NCI1/data/
  h_knn:
    current_percentage: 1.0
    1.0:
      k: 7
      alpha: 0.85
    # PageRank
    0.8:
      k: 3
      alpha: 0.9
    0.6:
      k: 5
      alpha: 0.95
    0.4:
      k: 7
      alpha: 0.95
    0.2:
      k: 7
      alpha: 0.85
  folder_results: ./results/h_knnV2/NCI1
proteins_tu:
  coordinator:
    dataset: proteins_tu
    params_edit_cost: !!python/tuple [1.0, 1.0, 1.0, 1.0, dirac]
    folder_dataset: ./data/PROTEINS/data/
  h_knn:
    current_percentage: 1.0
    1.0:
      k: 7
      alpha: 0.85
    # PageRank
    0.8:
      k: 3
      alpha: 0.65
    0.6:
      k: 5
      alpha: 0.4
    0.4:
      k: 7
      alpha: 0.95
    0.2:
      k: 7
      alpha: 0.85
  folder_results: ./results/h_knnV2/proteins_tu
enzymes:
  coordinator:
    dataset: enzymes
    params_edit_cost: !!python/tuple [1.0, 1.0, 1.0, 1.0, dirac]
    folder_dataset: ./data/ENZYMES/data/
  h_knn:
    current_percentage: 1.0
    1.0:
      k: 1
      alpha: 0.7
    # PageRank
    0.8:
      k: 3
      alpha: 0.65
    0.6:
      k: 5
      alpha: 0.4
    0.4:
      k: 7
      alpha: 0.95
    0.2:
      k: 7
      alpha: 0.85
  folder_results: ./results/h_knnV2/enzymes
collab:
  coordinator:
    dataset: collab
    params_edit_cost: !!python/tuple [1.0, 1.0, 1.0, 1.0, dirac]
    folder_dataset: ./data/COLLAB/data/
  k: 5
  folder_results: ./results/h_knnV2/collab
reddit_binary:
  coordinator:
    dataset: reddit_binary
    params_edit_cost: !!python/tuple [1.0, 1.0, 1.0, 1.0, dirac]
    folder_dataset: ./data/REDDIT-BINARY/data/
  k: 5
  folder_results: ./results/h_knnV2/reddit_binary
general:
  optimize: True
  percentages_to_opt: [0.2, 0.4, 0.6, 0.8, 1.0] #[1.0, 0.8, 0.6, 0.4, 0.2] # [0.2, 0.4, 0.6, 0.8]
  check_all_percentages: True
  num_cores: 12
  parallel: True
  deletion_strategy: compute_once
  save_to_html: False
  save_predictions: True
  tuning:
    alpha: [1, 20, 0.05]
    ks: [1, 3, 5, 7]
  current_percentage_to_opt: 1.0
  hierarchy_params:
    percentages: [1.0, 0.8, 0.6, 0.4, 0.2]
    centrality_measures: [pagerank, betweenness, random]
  current_centrality_measure: pagerank
