letter:
  coordinator:
    dataset: letter
    params_edit_cost: !!python/tuple [0.9, 0.9, 2.3, 2.3, euclidean]
    folder_dataset: ./data/Letter/Letter/HIGH/
  folder_results: ./results/draw/letter
AIDS:
  coordinator:
    dataset: AIDS
    params_edit_cost: !!python/tuple [1.1, 1.1, 0.1, 0.1, dirac]
    folder_dataset: ./data/AIDS/data/
  folder_results: ./results/draw/AIDS
mutagenicity:
  coordinator:
    dataset: mutagenicity
    params_edit_cost: !!python/tuple [11.0, 11.0, 1.1, 1.1, dirac]
    folder_dataset: ./data/Mutagenicity/data/
  folder_results: ./results/draw/mutagenicity
general:
  num_graphs: 10
  random_graph: True
  centrality_measure: pagerank

