letter:
  coordinator:
    dataset: letter
    params_edit_cost: !!python/tuple [1.0, 1.0, 1.0, 1.0, euclidean]
    folder_dataset: ./data/Letter/Letter/HIGH/
  k: 5
  best_alpha: 0.55
  linear_combination: [0.89,0.452,0.423,0.318,0.001]
  folder_results: ./results/knn_linear_combination/letter
AIDS:
  coordinator:
    dataset: AIDS
    params_edit_cost: !!python/tuple [1.0, 1.0, 1.0, 1.0, dirac]
    folder_dataset: ./data/AIDS/data/
  k: 1
  best_alpha: 0.7
  linear_combination: [0.595,0.53,0.419,0.335,0.623]
  folder_results: ./results/knn_linear_combination/AIDS
mutagenicity:
  coordinator:
    dataset: mutagenicity
    params_edit_cost: !!python/tuple [1.0, 1.0, 1.0, 1.0, dirac]
    folder_dataset: ./data/Mutagenicity/data/
    folder_labels: ./data/Mutagenicity/data/
  k: 5
  best_alpha: 0.60
  linear_combination: [1.0, 1.0, 1.0, 1.0, 1.0] # [0.637,0.369,0.219,0.512,0.738]
  folder_results: ./results/knn_linear_combination/mutagenicity
NCI1:
  coordinator:
    dataset: NCI1
    params_edit_cost: !!python/tuple [1.0, 1.0, 1.0, 1.0,  dirac]
    folder_dataset: ./data/NCI1/data/
    folder_labels: ./data/NCI1/data/
  k: 5
  best_alpha: 0.7
  linear_combination: [0.6, 0.1, 0.2, 0.4, 0.5] # [0.787,0.186,0.445,0.489,0.059]
  folder_results: ./results/knn_linear_combination/NCI1
general:
  hierarchy_params:
    percentages: [1.0, 0.8, 0.6, 0.4, 0.2]
    centrality_measures: [pagerank] # , betweenness]
  centrality_measure: pagerank
  parallel: True
  deletion_strategy: compute_once
  save_predictions: True
  optimization_strategy: linear
  do_optimization: False
  num_cores: 12
