cdef:
    str EXTENSION_GRAPHS
    str EXTENSION_SPLITS

    dict DEFAULT_FOLDERS
    dict DEFAULT_FOLDERS_LABELS

    dict LETTER_LBL_TO_CODE
    dict AIDS_LBL_TO_CODE
    dict MUTAGENICITY_LBL_TO_CODE
    dict NCI1_LBL_TO_CODE
    dict DEFAULT_LABELS_TO_CODE